//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int id { get; set; }
        public Nullable<short> Strength { get; set; }
        public Nullable<short> Agility { get; set; }
        public Nullable<short> Dexterity { get; set; }
        public Nullable<short> Health { get; set; }
        public Nullable<short> Beauty { get; set; }
        public Nullable<short> Intelligence { get; set; }
        public Nullable<short> Astral { get; set; }
        public Nullable<short> WillPower { get; set; }
        public Nullable<short> Detection { get; set; }
        public string Name { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<short> Level { get; set; }
        public Nullable<short> Personality { get; set; }
        public string Religion { get; set; }
        public string Homeland { get; set; }
        public string School { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Vitality { get; set; }
        public Nullable<short> Pain { get; set; }
        public Nullable<int> Specie { get; set; }
        public Nullable<int> Psi { get; set; }
        public Nullable<short> Stamina { get; set; }
    
        public virtual Psi Psi1 { get; set; }
        public virtual Species Species { get; set; }
        public virtual MagusClass MagusClass { get; set; }
    }
}
