//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagusClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MagusClass()
        {
            this.Character = new HashSet<Character>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> InitiatingBasic { get; set; }
        public Nullable<int> OffensiveBasic { get; set; }
        public Nullable<int> OffensiveMinPerLevel { get; set; }
        public Nullable<int> DefensiveBasic { get; set; }
        public Nullable<int> DefensiveMinPerLevel { get; set; }
        public Nullable<int> TargetingBasic { get; set; }
        public Nullable<int> FighterModPerLevel { get; set; }
        public Nullable<int> HealthBasic { get; set; }
        public Nullable<int> PainBasic { get; set; }
        public Nullable<int> PainPerLevelNumber { get; set; }
        public Nullable<int> PainPerLevelCube { get; set; }
        public Nullable<int> QualificationBasic { get; set; }
        public Nullable<int> QualificationPerLevel { get; set; }
        public Nullable<int> PercentagePerLevel { get; set; }
        public Nullable<int> Psi { get; set; }
        public Nullable<int> ClimbBasic { get; set; }
        public Nullable<int> FallingBasic { get; set; }
        public Nullable<int> JumpBasic { get; set; }
        public Nullable<int> SneakingBasic { get; set; }
        public Nullable<int> StealthBasic { get; set; }
        public Nullable<int> TightropeBasic { get; set; }
        public Nullable<int> PickpocketBasic { get; set; }
        public Nullable<int> ExploreTrapBasic { get; set; }
        public Nullable<int> ShutterBasic { get; set; }
        public Nullable<int> SecureDoorSearchBasic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Character { get; set; }
        public virtual Psi Psi1 { get; set; }
        public virtual Cube Cube { get; set; }
    }
}
