//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Species()
        {
            this.Character = new HashSet<Character>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<short> StrengthModifier { get; set; }
        public Nullable<short> StaminaModifier { get; set; }
        public Nullable<short> AgilityModifier { get; set; }
        public Nullable<short> DexterityModifier { get; set; }
        public Nullable<short> HealthModifier { get; set; }
        public Nullable<short> BeautyModifier { get; set; }
        public Nullable<short> IntelligenceModifier { get; set; }
        public Nullable<short> AstralModifier { get; set; }
        public Nullable<short> WillPowerModifier { get; set; }
        public Nullable<short> StrengthMax { get; set; }
        public Nullable<short> StaminaMax { get; set; }
        public Nullable<short> AgilityMax { get; set; }
        public Nullable<short> DexterityMax { get; set; }
        public Nullable<short> HealthMax { get; set; }
        public Nullable<short> BeautyMax { get; set; }
        public Nullable<short> IntelligenceMax { get; set; }
        public Nullable<short> AstralMax { get; set; }
        public Nullable<short> WillPowerMax { get; set; }
        public Nullable<short> DetectionMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Character { get; set; }
    }
}
